sudo: required
dist: trusty
language: python
python:
  - "3.4"
go:
  - "1.7"
services: mysql
env:
  - DJANGO=1.8
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go version
  - git clone git@github.com:OpenNetworking/go-ethereum.git
  - cd ./go-ethereum/ ; make evm
  - cd ..
  - pip install pep8
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database oracle;'
  - cp ./oracle/.env.default ./oracle/.env
  - sed -i 's/^ORACLE_DB=.*/ORACLE_DB=oracle/g' ./oracle/.env
  - sed -i 's/^MYSQL_HOST=.*/MYSQL_HOST=127.0.0.1/g' ./oracle/.env
  - sed -i 's/^MYSQL_PORT=.*/MYSQL_PORT=3306/g' ./oracle/.env
  - sed -i 's/^MYSQL_USER=.*/MYSQL_USER=root/g' ./oracle/.env
  - sed -i 's/^MYSQL_PASSWORD=.*/MYSQL_PASSWORD=/g' ./oracle/.env
  - sed -i 's/^SERVER_CONFIG_ENV=.*/SERVER_CONFIG_ENV=oracle.settings.production/g' ./oracle/.env
  - sed -i 's/^SECRET_KEY=.*/SECRET_KEY=SECRET_KEY/g' ./oracle/.env
  - sed -i 's/ALLOWED_HOSTS=.*/ALLOWED_HOSTS=/g' ./oracle/.env
  - sed -i 's/LOG_PATH=.*/LOG_PATH=/g' ./oracle/.env
  - sed -i 's/CONFIRMATION=.*/CONFIRMATION=1/g' ./oracle/.env
  - pep8 --exclude=migrations --ignore=E123,E133,E226,E241,E242,E402,E501,W503 ./oracle/
  - flake8 --exclude=migrations,settings,__init__.py --ignore=E123,E133,E226,E241,E242,E402,E501,W503 ./oracle/
script:
  - cd ./oracle
  - ./manage.py test
